### ISSUE TITLE
Utils.encode - Unable to call the encode function

### ISSUE THREAD

**Issue by sidstew** [xpring-eng/XpringKit#183]
I keep getting the error " Value of type 'Utils' has no member 'encode' " and cannot call the "encode" function.  Any help on being able to encode a classic address into an Xaddress would be awesome! 
I am using the code below within a function (per the documentation):

> let xAddress = Utils.encode(classicAddress: address, tag: tag)

**Comment by keefertaylor** [comment]
Hey. I am sorry for missing this issue. 

I think that this works on the latest release (it is passing our PR checks). Is it still an issue for you?

**Comment by sidstew** [comment]
Yep, works great now! Thanks for the followup
