### ISSUE TITLE
[FEATURE] Payment Channels?

### ISSUE THREAD

**Issue by dangell7** [xpring-eng/XpringKit#187]
Any timeline or interest in payment channels?

**Comment by keefertaylor** [comment]
Feature request noted - This isn't currently on our roadmap. 

We are working on building support for transactions which are not Payments. However, it remains relatively low priority for us.

**Comment by dangell7** [comment]
What is the difference? Or you mean you’re focusing on inter ledger protocol more? Are payments not a good use case? Seemed like payment channels were a good solve for my issue... would the ILP or “transactions” be better to use than payments?
