### ISSUE TITLE
How to convert privateKey to publicKey

### ISSUE THREAD

**Issue by q240252859** [xpring-eng/XpringKit#292]
How to convert privateKey to publicKey

**Comment by dangell7** [comment]
"Import" wallet from private key, then `wallet.publicKey`. I believe this should work.

**Comment by q240252859** [comment]
wallet from private key. Did not find a way, only found  private+ publicKey = wallet

**Comment by q240252859** [comment]
privateKey 输入的正则验证未找到

**Comment by dangell7** [comment]
You are correct.. Is there a reason you don't have the public key?

This repo https://github.com/MitchLang009/XRPKit has lots of code, I'm sure you could patch something together with XpringKit?
