### ISSUE TITLE
grpc-swift is no longer maintained

### ISSUE THREAD

**Issue by dangell7** [xpring-eng/XpringKit#295]
The library for SwiftGRPC is no longer maintained and they use a completely different library. I was having trouble integrating XpringKit into google products.

I had to Podfile install SwiftGRPC with a gRPC-Core version of `1.28.0` to get my pods to install correctly.

I was wondering if you are going to upgrade XpringKit to the new NIO protocol and the new grpc-Swift library?

**Comment by edpenano** [comment]
*bump

**Comment by dangell7** [comment]
Im using this now. https://github.com/dangell7/XRPKit
