### ISSUE TITLE
Failing to install XpringKit with Cocoapods

### ISSUE THREAD

**Issue by doniekelly** [xpring-eng/XpringKit#44]
I'm a bit lost as to why this is failing as nothing is obvious to me as to what is the issue. Any help appreciated. 

Thanks. Logs below after I run pod update 

```
Mac:XRPL donie$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing BigInt (5.0.0)
Installing BoringSSL-GRPC (0.0.3)
Installing SwiftGRPC (0.10.0)
Installing SwiftProtobuf (1.7.0)
Installing XpringKit (1.2.0)
Enter passphrase for key '/Users/donie/.ssh/id_rsa': 
Enter passphrase for key '/Users/donie/.ssh/id_rsa': 

[!] /bin/bash -c 
set -e
git submodule update --init --recursive && ./scripts/bundle_js.sh && ./scripts/regenerate_protos.sh

Submodule path 'xpring-common-js': checked out '4ce627e8ed33f44e9870fd84695a7d7c18f80884'
Submodule path 'xpring-common-js/xpring-common-protocol-buffers': checked out '3603db829677c41a7789746b858feb19a6e77845'
Submodule path 'xpring-common-protocol-buffers': checked out '41d8d7c316d11b79ab495110da24b9fb0f2c691b'
Bundling JS
>> Installing Node Dependencies

> fsevents@1.2.9 install /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/fsevents
> node install

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> tiny-secp256k1@1.1.3 install /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/tiny-secp256k1
> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."


> tiny-secp256k1@1.1.3 build /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/tiny-secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/native/addon.o
secp256k1 bindings compilation fail. Pure JS implementation will be used.

> grpc@1.24.2 install /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node" is installed via remote

> core-js@2.6.9 postinstall /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/ripple-binary-codec/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 962 packages from 1268 contributors and audited 7903 packages in 27.513s

1 package is looking for funding
  run `npm fund` for details

found 12 vulnerabilities (3 moderate, 9 high)
  run `npm audit fix` to fix them, or `npm audit` for details
>> Done Installing Node Dependencies
>> Running Webpack.

> xpring-common-js@1.1.7 webpack /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js
> npm run clean && ./scripts/regenerate_protos.sh && tsc && npx webpack


> xpring-common-js@1.1.7 clean /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js
> rm -rf ./generated ./dist ./build

Regenerating Protocol Buffers
Submodule 'xpring-common-js' (git@github.com:xpring-eng/xpring-common-js) registered for path 'xpring-common-js'
Submodule 'xpring-common-protocol-buffers' (git@github.com:xpring-eng/xpring-common-protocol-buffers) registered for path 'xpring-common-protocol-buffers'
Cloning into '/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js'...
Cloning into '/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-protocol-buffers'...
Submodule 'xpring-common-protocol-buffers' (http://github.com/xpring-eng/xpring-common-protocol-buffers) registered for path 'xpring-common-js/xpring-common-protocol-buffers'
Cloning into '/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/xpring-common-protocol-buffers'...
warning: redirecting to https://github.com/xpring-eng/xpring-common-protocol-buffers/
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.3.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
../native/addon.cpp:240:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:320:34: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                strict = info[3]->BooleanValue(Nan::GetCurrentContext()).FromJust();
                                               ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/donie/Library/Caches/node-gyp/13.3.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:82:36: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:142:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<2, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested here
        const auto flags = assumeCompression<2>(info, pA);
                           ^
/Users/donie/Library/Caches/node-gyp/13.3.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:82:36: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:174:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested here
        const auto flags = assumeCompression<1>(info, p);
                           ^
/Users/donie/Library/Caches/node-gyp/13.3.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:89:36: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:189:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value> >' requested here
        const auto flags = assumeCompression<1>(info);
                           ^
/Users/donie/Library/Caches/node-gyp/13.3.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:87:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
4 warnings and 4 errors generated.
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/13.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.0-83e16/xpring-common-js/node_modules/tiny-secp256k1
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donie/.npm/_logs/2019-12-12T21_18_00_480Z-debug.log
node-pre-gyp WARN Using needle for node-pre-gyp https download 
./scripts/regenerate_protos.sh: line 16: grpc_tools_node_protoc: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! xpring-common-js@1.1.7 webpack: `npm run clean && ./scripts/regenerate_protos.sh && tsc && npx webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the xpring-common-js@1.1.7 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donie/.npm/_logs/2019-12-12T21_18_14_506Z-debug.log


[!] Automatically assigning platform `iOS` with version `13.2` on target `XRPL` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Mac:XRPL donie$ 
```

**Comment by keefertaylor** [comment]
Hi!

Sorry that you're having trouble building. It looks like I'm not packaging a dependency correctly. I'm going to update the library so that doesn't happen (and I'll leave this issue open until that's resolved). 

In the meantime, you just need to install the protocol buffer compiler for node. You should be able to do that with:

```
$ npm i -g grpc-tools
```

**Comment by doniekelly** [comment]
Thank you. I’ll try that later this weekend. Appreciate you coming back to me.

**Comment by keefertaylor** [comment]
This task should get completed when #45 lands. 

I'll cut a new cocoapods build after that and push a release.

**Comment by doniekelly** [comment]
Thank you

**Comment by keefertaylor** [comment]
I just pushed [XpringKit v1.2.1 to CocoaPods](https://cocoapods.org/pods/xpringkit), which should solve your issue. Please re-open if you're still having trouble.

**Comment by doniekelly** [comment]
Hi @keefertaylor 

This is still not working and it cannot find protoc even thought the protobuf stuff is a dependency. Can you check it again as there may be other stuff as well?

donie$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.9.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.0.beta.2

Analyzing dependencies
Downloading dependencies
Installing BigInt (5.0.0)
Installing BoringSSL-GRPC (0.0.3)
Installing SwiftGRPC (0.10.0)
Installing SwiftProtobuf (1.7.0)
Installing XpringKit (1.2.1)
Enter passphrase for key '/Users/donie/.ssh/id_rsa': 
Enter passphrase for key '/Users/donie/.ssh/id_rsa': 
[!] /bin/bash -c 
set -e
git submodule update --init --recursive && ./scripts/bundle_js.sh && ./scripts/regenerate_protos.sh

Submodule path 'xpring-common-js': checked out '1710097e899ead9ffdb170b7a37e25bad931cebc'
Submodule path 'xpring-common-js/xpring-common-protocol-buffers': checked out '41d8d7c316d11b79ab495110da24b9fb0f2c691b'
Submodule path 'xpring-common-protocol-buffers': checked out '41d8d7c316d11b79ab495110da24b9fb0f2c691b'
Bundling JS
>> Installing Node Dependencies

> fsevents@1.2.11 install /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/fsevents
> node-gyp rebuild


> tiny-secp256k1@1.1.3 install /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/tiny-secp256k1
> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."


> tiny-secp256k1@1.1.3 build /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/tiny-secp256k1
> node-gyp rebuild

secp256k1 bindings compilation fail. Pure JS implementation will be used.

> grpc-tools@1.8.0 install /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/grpc-tools
> node-pre-gyp install

[grpc-tools] Success: "/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/grpc-tools/bin/grpc_tools.node" is installed via remote

> core-js@2.6.11 postinstall /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/ripple-binary-codec/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 887 packages from 1258 contributors and audited 7922 packages in 42.358s

9 packages are looking for funding
  run `npm fund` for details

found 8 vulnerabilities (2 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
>> Done Installing Node Dependencies
>> Running Webpack.

> xpring-common-js@1.1.15 webpack /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js
> npm run clean && ./scripts/regenerate_protos.sh && tsc && npx webpack


> xpring-common-js@1.1.15 clean /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js
> rm -rf ./generated ./dist ./build

Regenerating Protocol Buffers
All done!
Hash: 236db9688603d38682cb
Version: webpack 4.41.3
Time: 9461ms
Built at: 01/02/2020 09:47:47
     Asset      Size  Chunks                    Chunk Names
bundled.js  1.32 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = bundled.js
 [26] ./build/generated/xrp_amount_pb.js 4.62 KiB {0} [built]
 [42] ./build/generated/payment_pb.js 8.02 KiB {0} [built]
 [43] ./build/generated/signed_transaction_pb.js 6.22 KiB {0} [built]
 [44] ./build/generated/transaction_pb.js 9.98 KiB {0} [built]
 [45] ./build/src/utils.js 2.37 KiB {0} [built]
 [69] ./build/generated/currency_pb.js 537 bytes {0} [built]
 [70] ./build/generated/fiat_amount_pb.js 6.04 KiB {0} [built]
 [71] ./build/src/serializer.js 3.55 KiB {0} [built]
[120] ./build/src/index.js 2.72 KiB {0} [built]
[121] ./build/generated/account_info_pb.js 8.13 KiB {0} [built]
[124] ./build/generated/fee_pb.js 5.08 KiB {0} [built]
[125] ./build/generated/get_latest_validated_ledger_sequence_request_pb.js 4.59 KiB {0} [built]
[126] ./build/generated/get_account_info_request_pb.js 4.88 KiB {0} [built]
[127] ./build/generated/get_fee_request_pb.js 4.08 KiB {0} [built]
[128] ./build/generated/get_transaction_status_request_pb.js 5.06 KiB {0} [built]
    + 271 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundled.js (1.32 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.32 MiB)
      bundled.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
>> Done Running Webpack
Done Bundling JS
Copying Artifacts
Regenerating Common Protos...
Submodule 'xpring-common-js' (git@github.com:xpring-eng/xpring-common-js) registered for path 'xpring-common-js'
Submodule 'xpring-common-protocol-buffers' (git@github.com:xpring-eng/xpring-common-protocol-buffers) registered for path 'xpring-common-protocol-buffers'
Cloning into '/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js'...
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Cloning into '/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-protocol-buffers'...
Submodule 'xpring-common-protocol-buffers' (http://github.com/xpring-eng/xpring-common-protocol-buffers) registered for path 'xpring-common-js/xpring-common-protocol-buffers'
Cloning into '/Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/xpring-common-protocol-buffers'...
warning: redirecting to https://github.com/xpring-eng/xpring-common-protocol-buffers/
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/fsevents
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/donie/Library/Caches/CocoaPods/Pods/Release/XpringKit/1.2.1-37ca8/xpring-common-js/node_modules/tiny-secp256k1
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donie/.npm/_logs/2020-01-02T09_47_28_822Z-debug.log
node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

./scripts/regenerate_protos.sh: line 9: protoc: command not found


[!] Automatically assigning platform `iOS` with version `13.2` on target `XRPL` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
donie$

**Comment by keefertaylor** [comment]
Ok. Sorry about that. 

Other folks were having issues with getting this working over the holidays too. I can make this install process less fancy by checking in some of these derived artifacts. Re-opening this issue to track that work. 

I'm catching up from the holidays today and I'll try to get this done soon.

**Comment by keefertaylor** [comment]
I just cut and deployed 1.2.2 of XpringKit to CocoaPods which removes the need for any external tooling. Can you let me know if that gets you up and running?

**Comment by doniekelly** [comment]
Works now. Thank you
