### ISSUE TITLE
Send Escrow Transaction?

### ISSUE THREAD

**Issue by dangell7** [xpring-eng/XpringKit#50]
Just overviewing the sdk, I wasn't sure how to create an escrow transaction? Can I also use smart contracts with this sdk

**Comment by keefertaylor** [comment]
This isn't supported at the moment. I noted your feature request and we'll try to prioritize. 

Do you have a use case you're trying to ship? Or a time line for when you'd like support?

**Comment by dangell7** [comment]
Yeah I have an application that uses Ethereum. I decided to add XRP after the announcement of this wonderful SDK. However, now I'm realizing that this was probably a mistake as this sdk is not ready for production.
