### ISSUE TITLE
Web Socket for account balance?

### ISSUE THREAD

**Issue by dangell7** [xpring-eng/XpringKit#58]
I'm not familiar with your repo or grpc but I wanted to know how to call the subscribe command on the web socket? I want to call it for both account and transactions. Similar to how ethereum does it..

Is this implemented in your library? If not, how am I supposed to update the balance when a balance is updated on the chain? Just call the function again? Seems like alot of work went into the proto's and grpc but the functionality that developers need to execute a proper application on the blockchain is missing? Or am I missing something?

**Comment by keefertaylor** [comment]
gRPC is a RPC technology that supports streaming, which is similar to websockets. Over time, we'll add additional features in this library which support those sorts of use cases. That isn't possible today but we're constantly working to add support. 

If you want a streaming websockets API, [ripple-lib](https://github.com/ripple/ripple-lib) should allow you to have this functionality. Or you can just connect to a the [websockets on rippled directly](https://xrpl.org/websocket-api-tool.html#account_info).

**Comment by dangell7** [comment]
Yeah it seems that adding the websocket into my application to send and receive XRP is a must.

**Comment by dangell7** [comment]
Thank you.

**Comment by dangell7** [comment]
This should be done if not on the horizon
