### ISSUE TITLE
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs

### ISSUE THREAD

**Issue by cczufish** [xpring-eng/XpringKit#69]
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs

~~~

**Comment by cczufish** [comment]
pod install
Analyzing dependencies
[!] CDN: trunk Repo update failed - 2 error(s):
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/2/0/a/XpringKit/1.2.1/XpringKit.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Connection refused - connect(2) for "raw.githubusercontent.com" port 443)
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/2/0/a/XpringKit/1.2.2/XpringKit.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Connection refused - connect(2) for "raw.githubusercontent.com" port 443)

**Comment by cczufish** [comment]
Swift packages 


Showing All Messages
: https://github.com/xpring-eng/XpringKit.git has no Package.swift manifest for version 1.2.2

**Comment by keefertaylor** [comment]
Hi!

It looks like this is a problem with CocoaPods (`pod` is unable to clone the master repo). Several other reports of users having this issue: https://www.google.com/search?sxsrf=ACYBGNTgNhDRizF-9W3gqDD618DOnIYlvQ%3A1578540013166&ei=7ZsWXrjSCcGc5wLzq6qgBQ&q=CDN%3A+trunk+Repo+update+failed+&oq=CDN%3A+trunk+Repo+update+failed+&gs_l=psy-ab.3..0l3j0i22i30l7.2805.6334..6590...0.0..0.77.77.1......2....1..gws-wiz.VZvBKAuUXtM&ved=0ahUKEwj4_P3lx_XmAhVBzlkKHfOVClQQ4dUDCAs&uact=5

Can you try running through the suggestions from the CocoaPods  team here: https://github.com/CocoaPods/CocoaPods/issues/9319? 

Are you able to install other packages via CocoaPods?

**Comment by cczufish** [comment]
> Hi!
> 
> It looks like this is a problem with CocoaPods (`pod` is unable to clone the master repo). Several other reports of users having this issue: https://www.google.com/search?sxsrf=ACYBGNTgNhDRizF-9W3gqDD618DOnIYlvQ%3A1578540013166&ei=7ZsWXrjSCcGc5wLzq6qgBQ&q=CDN%3A+trunk+Repo+update+failed+&oq=CDN%3A+trunk+Repo+update+failed+&gs_l=psy-ab.3..0l3j0i22i30l7.2805.6334..6590...0.0..0.77.77.1......2....1..gws-wiz.VZvBKAuUXtM&ved=0ahUKEwj4_P3lx_XmAhVBzlkKHfOVClQQ4dUDCAs&uact=5
> 
> Can you try running through the suggestions from the CocoaPods team here: [CocoaPods/CocoaPods#9319](https://github.com/CocoaPods/CocoaPods/issues/9319)?
> 
> Are you able to install other packages via CocoaPods?

Thanks ,when I install other packages via cocoapods ,it success. I guess maybe network error

**Comment by keefertaylor** [comment]
I hit this tonight on my Mac. I don't know if it's a transient failure or not, but I ran:
```
pod repo update
```
Which pulls new CocoaPods URLs down to your machine and things started working afterwards.

**Comment by keefertaylor** [comment]
Closing this out as I haven't heard anything in a while. If you're still having trouble please feel free to reopen with additional details.
